### ISSUE TITLE
[Enhancement]: Add minimum requirements to README

### ISSUE THREAD

**Issue by rhmk** [redhat-et/microshift#243]
#### What would you like to be added:

Minimum specs (CPU,MEM, diskspace) to deploy minishift in the README and maybe install.sh

#### Why is this needed:

Helps to avoid problems if too small VM or  Computer is used for installation

**Comment by rootfs** [comment]
Sounds a good idea. I think 2 cores and 2GB is the min, based on what we have tested so far. @rhmk PR welcome :D

**Comment by husky-parul** [comment]
For me it was 3 GB. 
/assign @osilkin98

**Comment by osilkin98** [comment]
> If you just running the binary 2 cores and 2 GB. If you are going to build and run from source, it is 2 cores, 3 GB and 20 GB disk

When you're running from source for development purposes, 3 GB still ends up being too small. For my Vagrant setup, I allocated 4 cores and 6 GB, although you can probably get away with 5 GB since I've never seen it grow past that. Otherwise you will occasionally run into severed SSH connections, freezing builds, and failed launches.

**Comment by rhmk** [comment]
Great, thanks for your coments, which is really helpful for now. 
@rootfs Don't know how to create PR :-(
