### ISSUE TITLE
[BUG] setup selinux and env before starting microshift container via systemd

### ISSUE THREAD

**Issue by husky-parul** [redhat-et/microshift#434]
#### What happened:
Right now one has to manually run `CONFIG_ENV_ONLY=true ./install.sh` before starting `microshift-containerized.service`

#### What you expected to happen:
For `podman` deployment configure `selinux` policies before `systemd` calls  `ExecStart` step. 

#### Dependent on #432 and #433

**Comment by husky-parul** [comment]
I am to isolate the selinux configurations we need to have to run the container. If we plan to deprecate the `install.sh` the prep steps will be scripted to a file and called by systemd before `ExecStart` steps. As of now no selinux policies are set for container deployment. For testing I have set selinux off which needs to be fixed.

**Comment by fzdarsky** [comment]
Ack. Note, though, that install.sh installs the binary on the host (non-containerized), so its SELinux policies (which we've moved to an .rpm) wouldn't apply to containerised deployments. My suggestion would be to wait until #432 and #433 are fixed, because those should remove some of the SELinux pains.
